spring.application.name=RouteScheduleService
server.port=8088
spring.config.import=optional:configserver:http://localhost:8079
spring.cloud.config.server.git.skip-ssl-validation=true


spring.datasource.url=jdbc:mysql://localhost:3306/route_schedule_db?createDatabaseIfNotExist=true