spring.application.name=ApiGateway
server.port=8081

# ===============================
# Eureka Client
# ===============================
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ===============================
# Spring Cloud Gateway
# ===============================
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# -----Authentications  Service Routes ----- 
spring.cloud.gateway.server.webflux.routes[0].id=authentication-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTHENTICATIONSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# -----Citizen  Service Routes -----
spring.cloud.gateway.server.webflux.routes[1].id=authentication-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AUTHENTICATIONSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth/**

# -----Citizen  Service Routes -----
spring.cloud.gateway.server.webflux.routes[2].id=citizen-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://CITIZENSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/citizen/**

# ----- Compliance Audit Routes -----
spring.cloud.gateway.server.webflux.routes[3].id=compliance-audit-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://COMPLIANCEAUDITSERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/compliance/**,/audit/**

# ----- Notification Routes -----
spring.cloud.gateway.server.webflux.routes[4].id=notification-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://NOTIFICATIONSERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/notification/**


# ----- Program & Resource Service Routes -----
spring.cloud.gateway.server.webflux.routes[5].id=program-resource-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://PROGRAMRESOURCESERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/programs/**,/resources/**
# spring.cloud.gateway.routes[5].filters[0]=StripPrefix=0
#spring.cloud.gateway.server.webflux.routes[5].filters[0].name=CircuitBreaker
#spring.cloud.gateway.server.webflux.routes[5].filters[0].args.name=programResourceServiceCircuitBreaker
#spring.cloud.gateway.server.webflux.routes[5].filters[0].args.fallbackUri=forward:/fallback/program-resource-service-fallback

# ----- Report analytics Service Routes -----
spring.cloud.gateway.server.webflux.routes[6].id=report-analytics-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://REPORTANALYTICSSERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/report/**

# ----- Program & Resource Service Routes -----
spring.cloud.gateway.server.webflux.routes[7].id=route-schedule-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://ROUTESCHEDULESERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/route/**,/schedule/**

# ----- Program & Resource Service Routes -----
spring.cloud.gateway.server.webflux.routes[8].id=ticket-fare-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://TICKETFARESERVICE
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/ticket/**

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always