spring.application.name=ApiGateway
server.port=8081

jwt.secret=a96dd4552bd87db94d8a1ec4ed405b0233ccff6a1ce4f1fa811180da2db5aef8
# ===============================
# Eureka Client
# ===============================
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ===============================
# Spring Cloud Gateway
# ===============================

# ----- Authentication Service Routes -----
spring.cloud.gateway.server.webflux.routes[0].id=authentication-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTHENTICATIONSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**,/citizen/**,/users/**
spring.cloud.gateway.server.webflux.routes[0].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[0].filters[0].args.parts=0
spring.cloud.gateway.server.webflux.routes[0].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.name=authenticationServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[0].filters[1].args.fallbackUri=forward:/fallback/authentication-service-fallback
spring.cloud.gateway.server.webflux.routes[0].filters[2]=JwtAuthFilter


#
#
## ----- Citizen Service Routes -----
spring.cloud.gateway.server.webflux.routes[1].id=citizen-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://CITIZENSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/citizens-s/**
spring.cloud.gateway.server.webflux.routes[1].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.parts=0
spring.cloud.gateway.server.webflux.routes[1].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.name=citizenServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[1].filters[1].args.fallbackUri=forward:/fallback/citizen-service-fallback
spring.cloud.gateway.server.webflux.routes[1].filters[2]=JwtAuthFilter

# ----- Compliance Audit Routes -----
spring.cloud.gateway.server.webflux.routes[2].id=compliance-audit-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://COMPLIANCEAUDITSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/compliance/**,/audit/**
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.parts=0
spring.cloud.gateway.server.webflux.routes[2].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.name=complianceAuditServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[2].filters[1].args.fallbackUri=forward:/fallback/compliance-audit-service-fallback
spring.cloud.gateway.server.webflux.routes[2].filters[2]=JwtAuthFilter

# ----- Notification Service Routes -----
spring.cloud.gateway.server.webflux.routes[3].id=notification-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://NOTIFICATIONSERVICE
# Allow all notification paths and HTTP methods
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/notification/**
spring.cloud.gateway.server.webflux.routes[3].predicates[1]=Method=GET,POST,PUT,PATCH,DELETE
# JWT filter 
spring.cloud.gateway.server.webflux.routes[3].filters[0]=JwtAuthFilter

# ----- Program & Resource Service Routes -----
spring.cloud.gateway.server.webflux.routes[4].id=program-resource-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://PROGRAMRESOURCESERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/programs/**,/resources/**
spring.cloud.gateway.server.webflux.routes[4].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[4].filters[0].args.parts=0
spring.cloud.gateway.server.webflux.routes[4].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[4].filters[1].args.name=programResourceServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[4].filters[1].args.fallbackUri=forward:/fallback/program-resource-service-fallback
spring.cloud.gateway.server.webflux.routes[4].filters[2]=JwtAuthFilter

# ----- Report Analytics Service Routes -----
spring.cloud.gateway.server.webflux.routes[5].id=report-analytics-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://REPORTANALYTICSSERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/report/**
spring.cloud.gateway.server.webflux.routes[5].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[5].filters[0].args.parts=0
spring.cloud.gateway.server.webflux.routes[5].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[5].filters[1].args.name=reportAnalyticsServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[5].filters[1].args.fallbackUri=forward:/fallback/report-service-fallback
spring.cloud.gateway.server.webflux.routes[5].filters[2]=JwtAuthFilter

# ----- Route Schedule Service Routes -----
spring.cloud.gateway.server.webflux.routes[6].id=route-schedule-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://ROUTESCHEDULESERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/route/**,/schedule/**
spring.cloud.gateway.server.webflux.routes[6].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[6].filters[0].args.parts=0
spring.cloud.gateway.server.webflux.routes[6].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[6].filters[1].args.name=routeScheduleServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[6].filters[1].args.fallbackUri=forward:/fallback/route-schedule-service-fallback
spring.cloud.gateway.server.webflux.routes[6].filters[2]=JwtAuthFilter

# ----- Ticket Fare Service Routes -----
spring.cloud.gateway.server.webflux.routes[7].id=ticket-fare-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://TICKETFARESERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/ticket/**
spring.cloud.gateway.server.webflux.routes[7].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[7].filters[0].args.parts=0
spring.cloud.gateway.server.webflux.routes[7].filters[1].name=CircuitBreaker
spring.cloud.gateway.server.webflux.routes[7].filters[1].args.name=ticketFareServiceCircuitBreaker
spring.cloud.gateway.server.webflux.routes[7].filters[1].args.fallbackUri=forward:/fallback/ticket-fare-service-fallback
spring.cloud.gateway.server.webflux.routes[7].filters[2]=JwtAuthFilter

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always