spring.application.name=AuthenticationService
server.port=8082
spring.config.import=optional:configserver:http://localhost:8079
spring.cloud.config.server.git.skip-ssl-validation=true

jwt.secret=vdsuisdncbfsyias-dsgdsd37jdfvd-weynbsdfsdgfj
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service_db?createDatabaseIfNotExist=true

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always
