spring.application.name=ConfigServer
server.port=8079
spring.cloud.config.server.git.uri=https://github.com/Anantha-atole-03/CTS-ServerConfig.git
spring.cloud.config.server.git.skip-ssl-validation=true

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always