spring.application.name=NotificationService
server.port=8085

# Config Server (optional)
spring.config.import=optional:configserver:http://localhost:8079
spring.cloud.config.server.git.skip-ssl-validation=true

# ===============================
# Database Configuration (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/notification_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Mail Configuration
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=transportgovnotify@gmail.com
spring.mail.password=xhvvhtycwehnjvpp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# Eureka Configuration
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.main.allow-bean-definition-overriding=true