server.port=8083
spring.application.name=ComplianceAuditService
spring.config.import=optional:configserver:http://localhost:8079
spring.cloud.config.server.git.skip-ssl-validation=true

spring.datasource.url=jdbc:mysql://localhost:3306/compliance_audit_db?createDatabaseIfNotExist=true

management.endpoints.web.exposure.include=prometheus,health,info
management.endpoint.health.show-details=always


#chnage by mohit
feign.client.config.default.retryer=feign.Retryer$NeverRetry


# Increase Gateway Timeouts
spring.cloud.gateway.httpclient.connect-timeout=5000
spring.cloud.gateway.httpclient.response-timeout=10s

spring.devtools.restart.enabled=false
spring.cloud.openfeign.circuitbreaker.enabled=true

# Default circuit breaker config
resilience4j.circuitbreaker.instances.PROGRAMRESOURCESERVICE.register-health-indicator=true

resilience4j.circuitbreaker.instances.PROGRAMRESOURCESERVICE.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.PROGRAMRESOURCESERVICE.sliding-window-size=10

resilience4j.circuitbreaker.instances.PROGRAMRESOURCESERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.PROGRAMRESOURCESERVICE.minimum-number-of-calls=5


resilience4j.circuitbreaker.instances.PROGRAMRESOURCESERVICE.wait-duration-in-open-state=10s

# Calls allowed in HALF_OPEN
resilience4j.circuitbreaker.instances.PROGRAMRESOURCESERVICE.permitted-number-of-calls-in-half-open-state=3

# Automatically move to HALF_OPEN
resilience4j.circuitbreaker.instances.PROGRAMRESOURCESERVICE.automatic-transition-from-open-to-half-open-enabled=true





# Default circuit breaker config
resilience4j.circuitbreaker.instances.TICKETFARESERVICE.register-health-indicator=true

resilience4j.circuitbreaker.instances.TICKETFARESERVICE.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.TICKETFARESERVICE.sliding-window-size=10

resilience4j.circuitbreaker.instances.TICKETFARESERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.TICKETFARESERVICE.minimum-number-of-calls=5


resilience4j.circuitbreaker.instances.TICKETFARESERVICE.wait-duration-in-open-state=10s

# Calls allowed in HALF_OPEN
resilience4j.circuitbreaker.instances.TICKETFARESERVICE.permitted-number-of-calls-in-half-open-state=3

# Automatically move to HALF_OPEN
resilience4j.circuitbreaker.instances.TICKETFARESERVICE.automatic-transition-from-open-to-half-open-enabled=true





# Default circuit breaker config
resilience4j.circuitbreaker.instances.ROUTESCHEDULESERVICE.register-health-indicator=true

resilience4j.circuitbreaker.instances.ROUTESCHEDULESERVICE.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.ROUTESCHEDULESERVICE.sliding-window-size=10

resilience4j.circuitbreaker.instances.ROUTESCHEDULESERVICE.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ROUTESCHEDULESERVICE.minimum-number-of-calls=5


resilience4j.circuitbreaker.instances.ROUTESCHEDULESERVICE.wait-duration-in-open-state=10s

# Calls allowed in HALF_OPEN
resilience4j.circuitbreaker.instances.ROUTESCHEDULESERVICE.permitted-number-of-calls-in-half-open-state=3

# Automatically move to HALF_OPEN
resilience4j.circuitbreaker.instances.ROUTESCHEDULESERVICE.automatic-transition-from-open-to-half-open-enabled=true





